### ISSUE TITLE
"Embedded Mode" documentation as WordPress plugin

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/api-reference#12]
Related conversation in the Community Forum  → [Documentation related to Embedded Mode (or Frontity PHP plugin)](https://community.frontity.org/t/documentation-related-to-embedded-mode-or-frontity-php-plugin/4093)

**Comment by juanmaguitar** [comment]
Whenever the documentation of the Embedded Mode is avalable we should add this note to the [REST API settings of the `wp-source` package](https://api.frontity.org/frontity-packages/features-packages/wp-source#rest-api)

> If you are using Frontity using the [Embedded Mode](https://community.frontity.org/t/embedded-mode/1432), you do **not** normally have to set this property as your `state.source.url` will be the same as the `state.frontity.url`.

@michalczaplinski there's an [ongoing conversation](https://community.frontity.org/t/documentation-related-to-embedded-mode-or-frontity-php-plugin/4093) about how and when documenting Embedded Mode. While this documentation is not available, I prefer not to mention the Embedded Mode in the docs to avoid confussion. Nevertheless, I've added this note with your suggestion on the REST API parameters of the `wp-source` related to the Embedded Mode yo not forget adding this note, once thie proper documentation about the Embedded Mode is available

**Comment by mburridge** [comment]
Also refer to [this issue](https://github.com/frontity/docs/issues/232)

**Comment by mburridge** [comment]
And [this one](https://github.com/frontity/docs/issues/227)

**Comment by mburridge** [comment]
Embedded mode plugin done - closed #34 

To do: Add embedded mode section to [Architecture docs](https://docs.frontity.org/architecture)

**Comment by mburridge** [comment]
> To do: Add embedded mode section to Architecture docs

Done in https://github.com/frontity/docs/pull/296
