### ISSUE TITLE
Add documentation for `state.source.url`

### ISSUE THREAD

**Issue by michalczaplinski** [frontity/api-reference#7]
Feature discussion: https://community.frontity.org/t/make-the-backend-url-a-global-setting/2381/20

Pull request: https://github.com/frontity/frontity/pull/610

The pull request includes some details that are not relevant for conceptual understanding of this feature. The essentials are in the [packages/wp-source/src/state.ts](https://github.com/frontity/frontity/pull/610/files#diff-864830dce3fc3a4a80023b03a0c37b19767630fc28a252110b7ed03f3cbd80fe) and [packages/wp-source/types.ts](https://github.com/frontity/frontity/pull/610/files#diff-707a71640090b9826d1b450af00b2bc97a3c9778e587965a550de1736eb5d41c)

To give a brief overview:

1. Introduce a new property `state.source.url` in wp-source that points to the URL of the users' WordPress backend. The default value of that property is derived from `state.frontity.url`.

1. The default value of `state.source.api`  has changed. We now derive that value from the `state.source.url`. This should have no impact on existing applications, but has an important effect on new apps: You don't have to specify the `state.source.api`! 

   You now can just specify the `state.source.url` and the `state.source.api`  is computed from it by adding the "prefix" (see point 3. 🙂 ). 

1. Introduce a new property `state.wpSource.prefix` where the user can specify prefix of the REST API, for example `"/wp-json"` or `"?rest_route=/"`. The default value is `"/wp-json"`.

1. Introduce the `state.wpSource.api` and `state.wpSource.isWpCom`. For the moment their values are just derived from `state.source.api` and `state.source.isWpCom` respectively. This is added in preparation for the Source V2.

**Comment by SantosGuillamot** [comment]
@juanmaguitar Is this issue covered by [this guide](https://docs.frontity.org/guides/setting-url-wordpress-source-data) you published recently or are you keeping it opened because you're planning to work on more thing related to this? Maybe it could be nice to link to that guide from the [api reference](https://api.frontity.org/frontity-packages/features-packages/wp-source#state-source-url).

**Comment by juanmaguitar** [comment]
This Issue can be closed as it's been properly documented at:
- Proper [API documentation of the `wp-source` package ](https://api.frontity.org/frontity-packages/features-packages/wp-source#rest-api-settings)
- Guide [Setting the URL of the WordPress data source](https://docs.frontity.org/guides/setting-url-wordpress-source-data)
