### ISSUE TITLE
Write docs for the @frontity/yoast package

### ISSUE THREAD

**Issue by DAreRodz** [frontity/api-reference#9]
- Code Pull Request: https://github.com/frontity/frontity/pull/548
- Feature discussion: https://community.frontity.org/t/support-for-yoast-plugin-rest-api-fields/2626

The documentation URL linked in the README file of the package is this one (it should be created, doesn't exist yet): https://docs.frontity.org/api-reference-1/frontity-yoast

This package has two options: `transformLinks` and `onlyInSSR`. Both are explained in theTSDocs written in `types.ts`.

**Comment by mburridge** [comment]
@DAreRodz 

You refer to the `onlyInSSR` option - should that be `renderTags`? From what I can determine in the [feature discussion](https://community.frontity.org/t/support-for-yoast-plugin-rest-api-fields/2626) there was talk of an `onlyInSSR` option, but I guess this is what `renderTags` is?

**Comment by juanmaguitar** [comment]
@mburridge I guess we can close this issue 🎉

**Comment by mburridge** [comment]
Closing this as [PR #15](https://github.com/frontity/api-reference/pull/15) has been merged and closed and concludes this issue.
